language: ruby
sudo: false

cache:
  directories:
    - vendor/bundle

before_install:
  - "travis_retry gem update --system"
  - "bundle --version"
  - "if [ $RAILS_VERSION != 4.2 ]; then travis_retry gem update bundler; else gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true && gem install bundler -v '< 2'; fi"
  - "bundle --version"
install: bundle install --path=vendor/bundle --retry=3 --jobs=3

script:
  - bundle exec rubocop
  - bundle exec rake test

env:
  matrix:
    - "RAILS_VERSION=4.2"
    - "RAILS_VERSION=5.0"
    - "RAILS_VERSION=5.1"
    - "RAILS_VERSION=master"

rvm:
  - 2.3.5
  - 2.4.2
  - ruby-head

matrix:
  include:
  - { rvm: jruby-9.1.13.0, jdk: oraclejdk8, env: "RAILS_VERSION=4.2 JRUBY_OPTS='--dev -J-Xmx1024M --debug'" }
  - { rvm: jruby-9.1.13.0, jdk: oraclejdk8, env: "RAILS_VERSION=5.1 JRUBY_OPTS='--dev -J-Xmx1024M --debug'" }
  # See JRuby currently failing on Rails 5+ https://github.com/jruby/activerecord-jdbc-adapter/issues/708
  # - { rvm: jruby-9.1.13.0, jdk: oraclejdk8, env: "RAILS_VERSION=5.0 JRUBY_OPTS='--dev -J-Xmx1024M --debug'" }
  # - { rvm: jruby-head,     jdk: oraclejdk8, env: "RAILS_VERSION=5.1 JRUBY_OPTS='--dev -J-Xmx1024M --debug'" }
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - { rvm: 2.3.5, env: "RAILS_VERSION=master" }
    # See JRuby currently failing on Rails 5+ https://github.com/jruby/activerecord-jdbc-adapter/issues/708
    - { rvm: jruby-9.1.13.0, jdk: oraclejdk8, env: "RAILS_VERSION=5.1 JRUBY_OPTS='--dev -J-Xmx1024M --debug'" }
  fast_finish: true
